### PR TITLE
Add toggling of alternating layout

### PR DESCRIPTION
**Pull request by SCarv**
Hello friend. I've been using this script for a while and I wanted a way to toggle it with a single key like you toggle the other layouts in i3.

This way I can simply do in my config file:

bindsym $mod+f exec --no-startup-id ~/.i3/alternating_layouts.py

I don't know how to use i3's python module, so simply switching to another layout doesn't terminate the script.  You have to press the assigned key again (rerun the script). 

Hope you find it to be a good idea!

### CODE REVIEW

**Comment by olemartinorg** [comment]
Also, let's say you have the following setup:

```
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+f exec --no-startup-id ~/.i3/alternating_layouts.py
```

Why not just (probably not fully working, but you get the idea) do this:

```
bindsym $mod+s exec --no-startup-id killall ~/.i3/alternating_layouts.py; layout stacking
bindsym $mod+w exec --no-startup-id killall ~/.i3/alternating_layouts.py; layout tabbed
bindsym $mod+e exec --no-startup-id killall ~/.i3/alternating_layouts.py; layout toggle split
bindsym $mod+f exec --no-startup-id ~/.i3/alternating_layouts.py
```

**Comment by SCarv** [comment]
(one month later)
Hello again! Sorry but I was uselessly busy.

**Comment by olemartinorg** [comment]
Hi again! :-) Actually, i had forgotten all about this. If you look at #7, I added a pid-file option, you could probably expand on that?

**Comment by SCarv** [comment]
Okay certainly, I'll look into it!

**Pull request closed without merging**
